country_languages = {
    "USA": "en",
    "France": "fr",
    "Germany": "de",
    "Spain": "es",
    "China": "zh",
    "Brazil": "pt",
    "Japan": "ja",
    "India": "hi",
    "Italy": "it",
    "Russia": "ru",
    "Canada": "en",
    "Mexico": "es",
    "Australia": "en",
    "South Korea": "ko",
    "United Kingdom": "en",
    "Argentina": "es",
    "Turkey": "tr",
    "Indonesia": "id",
    "Netherlands": "nl",
    "Saudi Arabia": "ar",
    "Switzerland": "de",
    "Sweden": "sv",
    "Norway": "no",
    "Denmark": "da",
    "Austria": "de",
    "Belgium": "nl",
    "Finland": "fi",
    "Greece": "el",
    "Portugal": "pt",
    "Poland": "pl",
    "South Africa": "en",
    "Egypt": "ar",
    "Thailand": "th",
    "Vietnam": "vi",
    "Philippines": "en",
    "Malaysia": "ms",
    "Israel": "he",
    "Ireland": "en",
    "Singapore": "en",
    "New Zealand": "en",
    "United Arab Emirates": "ar",
    "Hong Kong": "zh",
    "Hungary": "hu",
    "Czech Republic": "cs",
    "Chile": "es",
    "Romania": "ro",
    "Pakistan": "ur",
    "Bangladesh": "bn",
    "Colombia": "es",
    "Belarus": "be",
    "Ukraine": "uk",
    "Iraq": "ar",
    "Kazakhstan": "kk",
    "Qatar": "ar",
    "Peru": "es",
    "Afghanistan": "ps",
    "Nigeria": "en",
    "Kenya": "sw",
    "Venezuela": "es",
    "Ecuador": "es",
    "Cuba": "es",
    "Bolivia": "es",
    "Dominican Republic": "es",
    "Czechia": "cs",
    "Norway": "no",
    "Slovakia": "sk",
    "Iran (Islamic Republic of)": "fa",
}
